# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 14:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_tmdb_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_videos',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='themoviedb videos'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='themoviedb info'),
        ),
    ]
