# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 20:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20150712_2126'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('Event', 'Favorite'),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['user', 'show', 'id'], 'verbose_name': 'favorite', 'verbose_name_plural': 'favorites'},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='shows.Show', verbose_name='show'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
