# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0003_auto_20150713_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='approximate_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='approximate price'),
        ),
    ]
